### ISSUE TITLE
Setup.php?step=2 fails

### ISSUE THREAD

**Issue by AZMel** [AcuGIS/jasper-report-publisher#1]
The error displayed in the browser is:

Warning: pg_query(): Query failed: ERROR: type "userlevel" already exists in /var/www/html/admin/setup.php on line 136
ERROR: type "userlevel" already exists

What can I do to get around this?

**Comment by DavidGhedini** [comment]
The script isn't intended to be run multiple times.  Simplest approach, if possible, is to reload the VM.
If not, you can change the database name in admin/incl/const.php and run admin/setup.php again.

**Comment by AZMel** [comment]
Thanks.  I ended recreating the container and was able to log in.

However, the sample reports do show in the dashboard but when I click on them I get:

 **HTTP Status 404 – Not Found
Type Status Report

Message The requested resource [/JasperReportsIntegration/report] is not available

Description The origin server did not find a current representation for the target resource or is not willing to disclose that one exists.

Apache Tomcat/9.0.96**

I did restart Tomcat through the services section and even restarted the server, which did not fix the issue.

**Comment by kaloyan13** [comment]
Can you check /var/log/apache/error.log or ${CATALINA_HOME}/logs/catalina.out for errors ?

**Comment by kaloyan13** [comment]
0b71bb2fbafcea4dfc2367ea57ad396077d2ede2 fixes samples to work with latest JRI.
To fix your install do the following:
1. Copy all files from [installer/sample](https://github.com/AcuGIS/jasper-report-publisher/tree/main/installer/sample) to ${CATALINA_HOME}/jasper_reports/reports/
2. chown -R tomcat:tomcat ${CATALINA_HOME}/jasper_reports/reports/

**Comment by DavidGhedini** [comment]
Closing as resolved
